version: "3"
services:
  database:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data/ # persist data even if container shuts down
  wager-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"
volumes:
  database_data:

