// Code generated by mockery v2.12.2. DO NOT EDIT.

package services

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repo "github.com/vitthalaa/wager-app/internal/repo"

	testing "testing"
)

// MockWagerRepo is an autogenerated mock type for the IWagerRepo type
type MockWagerRepo struct {
	mock.Mock
}

// CreateWager provides a mock function with given fields: ctx, wager
func (_m *MockWagerRepo) CreateWager(ctx context.Context, wager *repo.Wager) (*repo.Wager, error) {
	ret := _m.Called(ctx, wager)

	var r0 *repo.Wager
	if rf, ok := ret.Get(0).(func(context.Context, *repo.Wager) *repo.Wager); ok {
		r0 = rf(ctx, wager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Wager)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *repo.Wager) error); ok {
		r1 = rf(ctx, wager)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockWagerRepo creates a new instance of MockWagerRepo. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockWagerRepo(t testing.TB) *MockWagerRepo {
	mock := &MockWagerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
